version: '3'

x-networks:
  &network_name smart-personas_network

networks:
  smart-personas_network:
    name: *network_name

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=smart-personas_network"
    networks:
      *network_name :
        aliases:
          - review-generator.smart-personas.local
          - accessibility-reporter.smart-personas.local
          - a11y-ai.smart-personas.local

  docker-static:
    image: nginx:1.23-alpine3.17
    container_name: smart-personas_docker-static
    restart: unless-stopped
    ports:
      - 9999:80
    volumes:
      - ./static:/usr/share/nginx/html
    labels:
      - "traefik.http.routers.docker-static.entrypoints=docker-static"
    networks:
      - *network_name

  smart-personas-review-generator:
    image: smart-personas-review-generator
    build:
      context: ./services/smart-personas-review-generator
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smart-personas-review-generator.rule=Host(`review-generator.smart-personas.local`)"
      - "traefik.http.routers.smart-personas-review-generator.entrypoints=web"
      - "traefik.http.services.smart-personas-review-generator.loadbalancer.server.port=10000"
      - "traefik.docker.network=smart-personas_network"
    networks:
      - *network_name

  smart-personas-accessibility-reporter:
    image: smart-personas-accessibility-reporter
    build:
      context: ./services/smart-personas-accessibility-reporter
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smart-personas-accessibility-reporter.rule=Host(`accessibility-reporter.smart-personas.local`)"
      - "traefik.http.services.smart-personas-accessibility-reporter.loadbalancer.server.port=3000"
      - "traefik.http.routers.smart-personas-accessibility-reporter.entrypoints=web"
      - "traefik.docker.network=smart-personas_network"
    networks:
      - *network_name

  smart-personas-frontend:
    image: smart-personas-frontend
    build:
      context: ./services/smart-personas-frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smart-personas-frontend.rule=Host(`a11y-ai.smart-personas.local`)"
      - "traefik.http.routers.smart-personas-frontend.entrypoints=web"
      - "traefik.http.services.smart-personas-frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=smart-personas_network"
    networks:
      - *network_name
