GET http://localhost:3000/a11y-report?url=http://example.com
Content-Type: application/json

###

GET http://accessibility-reporter.local:80/a11y-report
Content-Type: application/json

###
GET http://127.0.0.1:1234/review?url=http://example.com
Content-Type: application/json

###
POST http://review-generator.local:80/review
Content-Type: application/json

{}

