<script setup lang="ts">
definePageMeta({
  layout: 'content',
})

const review = ref("As a social worker and someone with a vision impairment, I was excited to explore the Musikhaus Thomann website, Europe's largest music store. However, my enthusiasm quickly turned to disappointment as I encountered several accessibility issues that hindered my ability to navigate and interact with the site effectively. It's like trying to play a beautiful melody on a broken instrument – frustrating and disheartening.\n\nFirstly, the website violates the \"aria-allowed-role\" rule, which means that some elements cannot be intelligently interacted with by assistive technologies like my screen reader. It's like trying to have a conversation with someone who only speaks gibberish – impossible to understand and navigate.\n\nSecondly, the lack of accessible names for buttons and links makes it challenging for me to understand their purpose. It's like trying to find the right note in a song without any sheet music – a guessing game that leaves me feeling lost and disconnected.\n\nAdditionally, the poor color contrast on the website makes it difficult for me to read and comprehend the content. It's like trying to read sheet music in dim lighting – straining my eyes and causing unnecessary frustration.\n\nMoreover, the headings on the website are not properly marked up, making it hard for me to navigate and understand the structure of the page. It's like trying to follow a song without any clear sections or transitions – a jumbled mess that leaves me feeling disoriented.\n\nFurthermore, the lack of descriptive alt text for images is a huge barrier for me as a screen reader user. It's like attending a concert without being able to see the performers – missing out on important visual cues and information.\n\nThe inaccessible links prevent me from navigating the website effectively using only my keyboard. It's like trying to play a song with missing keys on a piano – limited and frustrating.\n\nIn conclusion, the Musikhaus Thomann website has the potential to be a harmonious experience for all users, but it falls flat in terms of accessibility. It's like trying to create a beautiful symphony with broken instruments – a missed opportunity to include everyone and make a meaningful impact. I urge the website developers to prioritize accessibility and ensure that all users, regardless of their abilities, can fully participate in the joy of music.")
</script>

<template>
  <Review :review="review" />
</template>